/**
 * Auto-generated image map
 * This file is automatically generated by scripts/generateImageMap.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run generate:images
 * Generated at: 2026-06-15T14:06:35.249Z
 */

export const projectImageMap: Record<string, string[]> = {
  'birthflow': [
    'birthflow.svg',
  ],
  'sydcommerce': [
    'sydcommerce-admin-orders.webp',
    'sydcommerce-admin.webp',
    'sydcommerce-cart.webp',
    'sydcommerce-categories.webp',
    'sydcommerce-dashboard.webp',
    'sydcommerce.webp',
  ],
  'sydpos': [
    'sydpos-cashier.webp',
    'sydpos-checkout.webp',
    'sydpos-dashboard.webp',
    'sydpos-inventory.webp',
    'sydpos-pos.webp',
    'sydpos-sale-success.webp',
    'sydpos-users.webp',
    'sydpos.webp',
  ],
};
