/**
 * Image Utilities
 * 
 * Helper functions for automatically loading project images from folders
 * Images are automatically discovered from public/images folders
 */

// Import auto-generated image map (generated by scripts/generateImageMap.js)
// This file is auto-generated - do not edit manually
import { projectImageMap } from './imageMap.generated';

/**
 * Automatically gets all images for a project folder
 * 
 * @param folderName - The folder name (e.g., 'sydcommerce', 'sydpos')
 * @returns Array of image paths
 */
export const getProjectImages = (folderName: string): string[] => {
  const images = projectImageMap[folderName.toLowerCase()];
  if (!images) return [];
  
  return images.map((image: string) => `/images/${folderName.toLowerCase()}/${image}`);
};

/**
 * Normalizes project title to folder name
 * Converts "SYD Commerce" -> "sydcommerce"
 * 
 * @param title - Project title
 * @returns Normalized folder name
 */
export const normalizeFolderName = (title: string): string => {
  return title
    .toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9]/g, '');
};

/**
 * Automatically gets images for a project by title
 * 
 * @param title - Project title (e.g., "SYD Commerce")
 * @returns Array of image paths
 */
export const getImagesByTitle = (title: string): string[] => {
  const folderName = normalizeFolderName(title);
  return getProjectImages(folderName);
};

