/**
 * Auto-generated image map
 * This file is automatically generated by scripts/generateImageMap.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run generate:images
 * Generated at: 2026-01-01T07:43:15.721Z
 */

export const projectImageMap: Record<string, string[]> = {
  'sydcommerce': [
    'sydcommerce-admin-orders.png',
    'sydcommerce-admin.png',
    'sydcommerce-cart.png',
    'sydcommerce-categories.png',
    'sydcommerce-dashboard.png',
    'sydcommerce.png',
  ],
  'sydpos': [
    'sydpos-cashier.png',
    'sydpos-checkout.png',
    'sydpos-dashboard.png',
    'sydpos-inventory.png',
    'sydpos-pos.png',
    'sydpos-sale-success.png',
    'sydpos-users.png',
    'sydpos.png',
  ],
};
