/**
 * Generates tree-shakeable inline SVG icon data from simple-icons at build time.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import {
  siCss,
  siDocker,
  siEslint,
  siFacebook,
  siFigma,
  siFlask,
  siGit,
  siGithub,
  siGodotengine,
  siHtml5,
  siJavascript,
  siMui,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siTailwindcss,
  siTypescript,
  siVercel,
  siVite,
} from 'simple-icons';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputFile = path.join(__dirname, '../src/data/inlineIcons.generated.ts');

const skillEntries = {
  Python: siPython,
  JavaScript: siJavascript,
  TypeScript: siTypescript,
  Java: null,
  'Godot Script': siGodotengine,
  Godot: siGodotengine,
  HTML: siHtml5,
  CSS: siCss,
  React: siReact,
  'Next.js': siNextdotjs,
  Tailwind: siTailwindcss,
  TailwindCSS: siTailwindcss,
  Flask: siFlask,
  'Material UI': siMui,
  MUI: siMui,
  'Node.js': siNodedotjs,
  NodeJS: siNodedotjs,
  PostgreSQL: siPostgresql,
  MySQL: siMysql,
  Prisma: siPrisma,
  Git: siGit,
  GitHub: siGithub,
  'Git & GitHub': siGithub,
  npm: siNpm,
  NPM: siNpm,
  ESLint: siEslint,
  Docker: siDocker,
  Vite: siVite,
  Vercel: siVercel,
  Figma: siFigma,
  'Visual Studio Code': null,
  'Microsoft Office': null,
};

/**
 * Serializes icon metadata for TypeScript output.
 *
 * @param icon - Simple Icons entry
 * @returns Serialized object literal string
 */
function serializeIcon(icon) {
  const escapedPath = icon.path.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `{ title: '${icon.title}', hex: '${icon.hex}', path: '${escapedPath}' }`;
}

/**
 * Writes inline icon map used by Skills and Contact components.
 */
function generateInlineIcons() {
  let content = `/**
 * Auto-generated inline icon map
 * Generated by scripts/generateInlineIcons.js — do not edit manually
 * Generated at: ${new Date().toISOString()}
 */

export interface InlineIcon {
  title: string;
  hex: string;
  path: string;
}

export const socialIcons = {
  github: ${serializeIcon(siGithub)},
  facebook: ${serializeIcon(siFacebook)},
} as const;

export const skillIconMap: Record<string, InlineIcon | null> = {
`;

  for (const [skillName, icon] of Object.entries(skillEntries)) {
    const value = icon ? serializeIcon(icon) : 'null';
    content += `  '${skillName.replace(/'/g, "\\'")}': ${value},\n`;
  }

  content += `};\n`;

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, content, 'utf-8');
  console.log(`✅ Generated inline icons at: ${outputFile}`);
}

generateInlineIcons();
