/**
 * Build-time script to automatically discover images in public/images folders
 * This script scans the public/images directory and generates a TypeScript file
 * with all discovered images, so you don't need to manually add them.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const imagesDir = path.join(__dirname, '../public/images');
const outputFile = path.join(__dirname, '../src/utils/imageMap.generated.ts');

/**
 * Writes generated content only when it differs from the current file.
 */
function writeFileIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) {
    return false;
  }

  fs.writeFileSync(filePath, content, 'utf-8');
  return true;
}

/**
 * Recursively get all image files from a directory
 */
function getImageFiles(dir, basePath = '') {
  const files = [];
  const items = fs.readdirSync(dir, { withFileTypes: true });

  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    const relativePath = path.join(basePath, item.name);

    if (item.isDirectory()) {
      // Recursively scan subdirectories
      files.push(...getImageFiles(fullPath, relativePath));
    } else if (item.isFile()) {
      // Check if it's an image file
      const ext = path.extname(item.name).toLowerCase();
      const isGeneratedThumbnail = /-card-\d+\.webp$/i.test(item.name);

      if (!isGeneratedThumbnail && ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg'].includes(ext)) {
        files.push(relativePath);
      }
    }
  }

  return files;
}

/**
 * Group images by folder, preferring WebP over duplicate raster sources.
 */
function groupImagesByFolder(imagePaths) {
  const grouped = {};

  for (const imagePath of imagePaths) {
    const parts = imagePath.split(path.sep);
    if (parts.length <= 1) {
      continue;
    }

    const folderName = parts[0];
    const fileName = parts.slice(1).join(path.sep);
    const extension = path.extname(fileName).toLowerCase();
    const baseName = fileName.slice(0, -extension.length);

    if (!grouped[folderName]) {
      grouped[folderName] = new Map();
    }

    const folderMap = grouped[folderName];
    const existing = folderMap.get(baseName);

    if (!existing || extension === '.webp') {
      folderMap.set(baseName, fileName);
    }
  }

  const normalized = {};
  for (const [folder, fileMap] of Object.entries(grouped)) {
    normalized[folder] = [...fileMap.values()];
  }

  return normalized;
}

/**
 * Generate TypeScript file with image mappings
 */
function generateImageMap() {
  try {
    // Ensure images directory exists
    if (!fs.existsSync(imagesDir)) {
      console.warn(`⚠️  Images directory does not exist: ${imagesDir}`);
      console.warn('   Creating empty image map...');
      
      // Create empty map if directory doesn't exist
      const emptyMap = `/**
 * Auto-generated image map
 * This file is automatically generated by scripts/generateImageMap.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run generate:images
 */

export const projectImageMap: Record<string, string[]> = {};
`;
      writeFileIfChanged(outputFile, emptyMap);
      console.log(`✅ Created empty image map at: ${outputFile}`);
      return;
    }

    const allImages = getImageFiles(imagesDir);
    const grouped = groupImagesByFolder(allImages);

    // Generate TypeScript content
    let tsContent = `/**
 * Auto-generated image map
 * This file is automatically generated by scripts/generateImageMap.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run generate:images
 */

export const projectImageMap: Record<string, string[]> = {\n`;

    // Sort folders for consistent output
    const sortedFolders = Object.keys(grouped).sort();
    
    if (sortedFolders.length === 0) {
      tsContent = tsContent.replace('{\n', '{};\n');
    } else {
      for (const folder of sortedFolders) {
        const images = grouped[folder].sort();
        tsContent += `  '${folder}': [\n`;
        for (const image of images) {
          // Escape single quotes in filenames
          const escapedImage = image.replace(/'/g, "\\'").replace(/\\/g, '/');
          tsContent += `    '${escapedImage}',\n`;
        }
        tsContent += `  ],\n`;
      }
      tsContent += `};\n`;
    }

    // Ensure output directory exists
    const outputDir = path.dirname(outputFile);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write to file
    writeFileIfChanged(outputFile, tsContent);
    console.log(`✅ Generated image map with ${sortedFolders.length} folders and ${allImages.length} images`);
    console.log(`   Output: ${outputFile}`);
  } catch (error) {
    console.error('❌ Error generating image map:', error.message);
    process.exit(1);
  }
}

// Run the script
generateImageMap();

export { generateImageMap };

